# Sync shared agent definitions from ~\.agents\agents (source of truth) to
# runtimes with NATIVE sub-agent support:
#   Claude Code  ~\.claude\agents\<name>.md   (frontmatter: name, description)
#   OpenCode     ~\.config\opencode\agent\<name>.md (frontmatter: description, mode: subagent)
#
# Safety rules:
#   - Only writes a file if it does NOT exist or was generated by this script
#     (marked with the GENERATOR-MARK). Hand-placed agent files are never
#     overwritten.
#   - Runtimes without native sub-agents are NOT faked; the shared definitions
#     remain readable markdown (agents may follow them as inline roles).
#
# -TargetHome: override the "home" root (used by tests to run in a sandbox).
[CmdletBinding()]
param([string]$TargetHome = $env:USERPROFILE)
$ErrorActionPreference = 'Stop'

$shared = Join-Path $PSScriptRoot 'agents'
if (-not (Test-Path $shared)) { throw "Shared agents dir not found: $shared" }
$genFiles = Get-ChildItem $shared -Filter '*.md' -File | Sort-Object Name
if (-not $genFiles) { throw "No agent definitions found under $shared" }

$GENERATED = '<!-- GENERATED by ~\.agents\sync-agents.ps1 - safe to regenerate -->'

function Test-ValidDef([System.IO.FileInfo]$f, [hashtable]$meta) {
    if (-not $meta.name -or -not $meta.description) { return $false }
    if ($f.BaseName -ne $meta.name) { return $false }
    if (-not (Select-String -Path $f.FullName -Pattern '(?m)^## Purpose$' -Quiet)) { return $false }
    if (-not (Select-String -Path $f.FullName -Pattern '(?m)^## Forbidden behavior$' -Quiet)) { return $false }
    if (-not (Select-String -Path $f.FullName -Pattern '(?m)^## Output expectations$' -Quiet)) { return $false }
    return $true
}

function Get-DefMeta([System.IO.FileInfo]$f) {
    $meta = @{}
    $lines = Get-Content $f.FullName
    if ($lines[0] -ne '---') { throw "No YAML frontmatter in: $($f.Name)" }
    for ($i = 1; $i -lt $lines.Count -and $lines[$i] -ne '---'; $i++) {
        if ($lines[$i] -match '^(\S[^:]*):\s*(.+)$') { $meta[$Matches[1].Trim()] = $Matches[2].Trim() }
    }
    return $meta
}

function Get-Body([System.IO.FileInfo]$f) {
    $raw = Get-Content $f.FullName -Raw
    return $raw.Substring($raw.IndexOf('---', 4) + 3).TrimStart()
}

$report = [ordered]@{}
$names = @()
foreach ($f in $genFiles) {
    $meta = Get-DefMeta $f
    if (-not (Test-ValidDef $f $meta)) { throw "Invalid agent definition: $($f.Name)" }
    $names += $meta.name
    $body = Get-Body $f

    # Claude Code: copy with frontmatter it natively parses.
    $cc = Join-Path $TargetHome '.claude\agents'
    if (-not (Test-Path $cc)) { New-Item -ItemType Directory -Path $cc -Force | Out-Null }
    $ccPath = Join-Path $cc $f.Name
    $ccContent = "---`nname: $($meta.name)`ndescription: $($meta.description)`n---`n`n$GENERATED`n`n$body"
    if ((Test-Path $ccPath) -and -not (Select-String -Path $ccPath -SimpleMatch 'GENERATED by ~\.agents\sync-agents.ps1' -Quiet)) {
        $report["Claude $($meta.name)"] = 'skipped (hand-placed)'
    } else {
        $existing = if (Test-Path $ccPath) { (Get-Content $ccPath -Raw) } else { $null }
        if ($existing -ne $null -and $existing.TrimEnd() -eq $ccContent.TrimEnd()) { $report["Claude $($meta.name)"] = 'unchanged' }
        else { Set-Content -Path $ccPath -Value $ccContent -Encoding UTF8; $report["Claude $($meta.name)"] = 'written' }
    }

    # OpenCode: subagent-mode frontmatter + body.
    $oc = Join-Path $TargetHome '.config\opencode\agent'
    if (-not (Test-Path $oc)) { New-Item -ItemType Directory -Path $oc -Force | Out-Null }
    $ocPath = Join-Path $oc $f.Name
    $ocContent = "---`ndescription: $($meta.description)`nmode: subagent`n---`n`n$GENERATED`n`n$body"
    if ((Test-Path $ocPath) -and -not (Select-String -Path $ocPath -SimpleMatch 'GENERATED by ~\.agents\sync-agents.ps1' -Quiet)) {
        $report["OpenCode $($meta.name)"] = 'skipped (hand-placed)'
    } else {
        $existing = if (Test-Path $ocPath) { (Get-Content $ocPath -Raw) } else { $null }
        if ($existing -ne $null -and $existing.TrimEnd() -eq $ocContent.TrimEnd()) { $report["OpenCode $($meta.name)"] = 'unchanged' }
        else { Set-Content -Path $ocPath -Value $ocContent -Encoding UTF8; $report["OpenCode $($meta.name)"] = 'written' }
    }
}

$dups = $names | Group-Object | Where-Object Count -gt 1
if ($dups) { throw "Duplicate agent definitions: $(($dups | % Name) -join ', ')" }

$report.GetEnumerator() | ForEach-Object { '{0,-16} {1}' -f $_.Value, $_.Key }
Write-Host "Agents synced: $($names.Count) -> $($names -join ', ')"
