# Sync shared rules from ~\.agents\rules (source of truth) into agent
# instruction files. Idempotent. Only replaces content inside clearly marked
# generated blocks; never touches user-authored content outside them.
#
# Targets (only agents with a global instruction file are adapted):
#   Claude Code  ~\.claude\CLAUDE.md
#   Codex        ~\.codex\AGENTS.md
#   OpenCode     ~\.config\opencode\AGENTS.md
#   Qwen Code    ~\.qwen\QWEN.md (generated pointer file from sync-adapters.ps1)
#
# -TargetHome: override the "home" root (used by tests to run in a sandbox).
[CmdletBinding()]
param([string]$TargetHome = $env:USERPROFILE)
$ErrorActionPreference = 'Stop'

$shared = Join-Path $PSScriptRoot 'rules'
if (-not (Test-Path $shared)) { throw "Shared rules dir not found: $shared" }
$ruleFiles = Get-ChildItem $shared -Filter '*.md' -File | Sort-Object Name
if (-not $ruleFiles) { throw "No rule files found under $shared" }

$START = '<!-- shared-agents:rules:START (generated by sync-rules.ps1 - do not edit inside) -->'
$END   = '<!-- shared-agents:rules:END -->'

function Test-WellFormed([System.IO.FileInfo]$f) {
    $raw = Get-Content $f.FullName -Raw
    if (-not $raw) { return $false }
    if ($raw -notmatch '(?m)^#\s+\S') { return $false }   # must start with a heading
    return ($raw -notmatch '(?i)(api[_-]?key|password|token)\s*[:=]\s*\S')
}

foreach ($f in $ruleFiles) {
    if (-not (Test-WellFormed $f)) { throw "Malformed rule file (empty, missing heading, or looks like it contains a secret): $($f.Name)" }
}

function Build-Block {
    $parts = foreach ($f in $ruleFiles) {
        "## $($f.BaseName)`n"
        (Get-Content $f.FullName -Raw).TrimEnd()
        ""
    }
    $body = ($parts -join "`n").TrimEnd()
    return "$START`n$body`n$END"
}

function Sync-RulesFile([string]$path, [switch]$PointerFile) {
    # Ensure the target directory exists (needed for sandboxes).
    $parent = Split-Path $path -Parent
    if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
    $block = Build-Block
    $existing = if (Test-Path $path) { Get-Content $path -Raw } else { $null }

    if (-not $existing) {
        # File does not exist: create it as a fully-generated artifact.
        $header = if ($PointerFile) { $null } else {
            "# Agent instructions`n`nRules section below is generated from ~\.agents\rules by sync-rules.ps1.`n"
        }
        Set-Content -Path $path -Value (($header, $block) -join "`n").TrimEnd() -Encoding UTF8
        return 'created'
    }

    $sIdx = $existing.IndexOf($START)
    $eIdx = $existing.IndexOf($END)
    if ($sIdx -ge 0 -and $eIdx -ge 0) {
        # Replace only the existing generated block.
        $new = $existing.Remove($sIdx, $eIdx + $END.Length - $sIdx).Insert($sIdx, $block)
        if ($new -eq $existing) { return 'unchanged' }
        Set-Content -Path $path -Value $new -Encoding UTF8 -NoNewline
        return 'updated'
    }
    if ($sIdx -ge 0 -xor $eIdx -ge 0) {
        throw "Malformed generated block (unmatched marker) in: $path"
    }
    # No block yet: append one, preserving all user content.
    Add-Content -Path $path -Value "`n$block" -Encoding UTF8
    return 'appended'
}

$report = [ordered]@{}
$report['Claude Code CLAUDE.md']  = Sync-RulesFile (Join-Path $TargetHome '.claude\CLAUDE.md')
$report['Codex AGENTS.md']        = Sync-RulesFile (Join-Path $TargetHome '.codex\AGENTS.md')
$report['OpenCode AGENTS.md']     = Sync-RulesFile (Join-Path $TargetHome '.config\opencode\AGENTS.md')
$report['Qwen Code QWEN.md']      = Sync-RulesFile (Join-Path $TargetHome '.qwen\QWEN.md') -PointerFile

$report.GetEnumerator() | ForEach-Object { '{0,-8} {1}' -f $_.Value, $_.Key }
Write-Host "Rules synced: $($ruleFiles.Count) -> $($ruleFiles.Name -join ', ')"
