# Sync adapters from ~\.agents\skills (source of truth) to per-agent dirs.
# Idempotent. Never touches agent-owned content (e.g. Codex .system).

[CmdletBinding()]
param([string]$TargetHome = $env:USERPROFILE)
$ErrorActionPreference = 'Stop'

$shared = Join-Path $env:USERPROFILE '.agents\skills'
if (-not (Test-Path $shared)) { throw "Shared skills dir not found: $shared" }
$skillNames = Get-ChildItem $shared -Directory | Where-Object { Test-Path (Join-Path $_.FullName 'SKILL.md') } |
    Select-Object -ExpandProperty Name
if (-not $skillNames) { throw "No skills found under $shared" }

function Test-SamePath([string]$a, [string]$b) {
    $na = [IO.Path]::GetFullPath($a).TrimEnd('\').ToLowerInvariant()
    $nb = [IO.Path]::GetFullPath($b).TrimEnd('\').ToLowerInvariant()
    return ($na -eq $nb)
}

# Deletes ONLY the junction itself (cmd rmdir never recurses into the target).
function Remove-Junction([string]$path) {
    cmd /c rmdir "`"$path`"" | Out-Null
    if (Test-Path $path) { throw "Failed to remove junction: $path" }
}

function Test-SameTree([string]$a, [string]$b) {
    $left = @{}; $right = @{}
    Get-ChildItem $a -Recurse -File | ForEach-Object { $left[$_.FullName.Substring($a.Length + 1)] = (Get-FileHash $_.FullName -Algorithm SHA256).Hash }
    Get-ChildItem $b -Recurse -File | ForEach-Object { $right[$_.FullName.Substring($b.Length + 1)] = (Get-FileHash $_.FullName -Algorithm SHA256).Hash }
    $keys = @($left.Keys + $right.Keys | Sort-Object -Unique)
    return (@($keys | Where-Object { $left[$_] -ne $right[$_] }).Count -eq 0)
}

function New-Junction([string]$path, [string]$target) {
    if (Test-Path $path) {
        $item = Get-Item $path -Force
        if ($item.LinkType -eq 'Junction' -and $item.Target) {
            if (Test-SamePath @($item.Target)[0] $target) { return 'exists' }
        }
        throw "Refusing to overwrite non-junction or wrong-target item: $path"
    }
    New-Item -ItemType Junction -Path $path -Target $target | Out-Null
    return 'created'
}

$report = [ordered]@{}

# 1. OpenCode: whole-dir junction
$ocSkills = Join-Path $TargetHome '.config\opencode\skills'
$report[$ocSkills] = New-Junction $ocSkills $shared

# 2. Claude Code: whole-dir junction
$ccSkills = Join-Path $TargetHome '.claude\skills'
$report[$ccSkills] = New-Junction $ccSkills $shared

# 3. Codex: per-skill junctions (dir also contains Codex-owned .system)
$codexSkills = Join-Path $TargetHome '.codex\skills'
if (-not (Test-Path $codexSkills)) { New-Item -ItemType Directory -Path $codexSkills | Out-Null }
foreach ($name in $skillNames) {
    $p = Join-Path $codexSkills $name
    $target = Join-Path $shared $name
    if (Test-Path $p) {
        $item = Get-Item $p -Force
        if ($item.LinkType -ne 'Junction') {
            if (-not (Test-SameTree $p $target)) {
                throw "Refusing to replace divergent Codex skill directory: $p"
            }
            Remove-Item $p -Recurse -Force
        } elseif (-not (Test-SamePath @($item.Target)[0] $target)) {
            Remove-Junction $p
        }
    }
    $report[$p] = New-Junction $p $target
}
# Remove Codex junctions pointing at shared but whose skill no longer exists
foreach ($child in Get-ChildItem $codexSkills -Force) {
    $item = Get-Item $child.FullName -Force
    $t = @($item.Target)[0]
    if ($item.LinkType -eq 'Junction' -and ($skillNames -notcontains $item.Name) -and
        $t -and (Test-SamePath $t $shared)) {
        Remove-Junction $item.FullName
        Write-Host "Removed stale Codex junction: $($item.Name)"
    }
}

# 4. Qwen Code: global pointer artifact (generated; has no native skills dir)
$qwenMd = Join-Path $TargetHome '.qwen\QWEN.md'
$pointerLines = @(
    '# Shared skills pointer (generated by ~\.agents\sync-adapters.ps1 - do not hand-edit)',
    '',
    "You have access to reusable engineering skills stored at $shared.",
    'Each subfolder contains a SKILL.md with instructions. Before starting non-trivial',
    'work, check whether one applies (continue, plan, implement, test, verify, checkpoint,',
    'review, cold-review, audit, research, context-management, task-delegation) and follow it.',
    '',
    'Project memory convention: read/update .agent/CHECKPOINT.md (current state) and',
    '.agent/DECISIONS.md (append-only decisions) in the project root when they exist.'
)
$pointer = $pointerLines -join "`r`n"
$existingPointer = if (Test-Path $qwenMd) { Get-Content $qwenMd -Raw } else { '' }
# Preserve a rules block injected by sync-rules.ps1 across regeneration.
$rulesBlock = ''
$rs = $existingPointer.IndexOf('<!-- shared-agents:rules:START')
$re = $existingPointer.IndexOf('<!-- shared-agents:rules:END -->')
if ($rs -ge 0 -and $re -ge 0) {
    $rulesBlock = "`r`n" + $existingPointer.Substring($rs, $re + '<!-- shared-agents:rules:END -->'.Length - $rs) + "`r`n"
}
if ($existingPointer -match 'sync-adapters\.ps1') {
    Set-Content -Path $qwenMd -Value ($pointer + $rulesBlock) -Encoding UTF8
    $report[$qwenMd] = 'updated'
} elseif ($existingPointer) {
    Add-Content -Path $qwenMd -Value "`n$pointer" -Encoding UTF8
    $report[$qwenMd] = 'appended'
} else {
    $qwenDir = Split-Path $qwenMd -Parent
    if (-not (Test-Path $qwenDir)) { New-Item -ItemType Directory -Path $qwenDir -Force | Out-Null }
    Set-Content -Path $qwenMd -Value $pointer -Encoding UTF8
    $report[$qwenMd] = 'created'
}

$report.GetEnumerator() | ForEach-Object { '{0,-7} {1}' -f $_.Value, $_.Key }
Write-Host "`nSkills synced: $($skillNames.Count) -> $($skillNames -join ', ')"
